version: 2

updates:

* package-ecosystem: "pip"
  directory: "/"

  schedule:
  interval: "daily"

  open-pull-requests-limit: 10

  labels:

  * dependencies
  * python

  commit-message:
  prefix: "deps"

  groups:
  minor-patch:
  update-types:
  - minor
  - patch

  ignore:

  * dependency-name: "*"
    update-types:

    * version-update:semver-major
